name: Process Data

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run data processing script
      run: |
        python filter_data.py  # Call filter data program

    - name: Upload filtered data
      uses: actions/upload-artifact@v2
      with:
        name: filtered-data
        path: filtered_data.json
